library(bindata)

n = 10000
k = 1000

cors = matrix(0.5, k, k)
for (x in 1: k) {
  cors[x, x] = 1
}

means = matrix(0.1, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_1_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_1_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_1_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_1_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.3, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_3_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_3_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_3_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_3_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.5, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_5_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_5_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_5_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_5_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.7, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_7_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_7_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_7_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_7_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.9, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_9_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_9_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_9_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph5_9_5.txt", row.names=FALSE, col.names=FALSE, sep=",")


cors = matrix(0.7, k, k)
for (x in 1: k) {
  cors[x, x] = 1
}

means = matrix(0.1, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_1_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_1_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_1_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_1_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.3, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_3_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_3_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_3_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_3_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.5, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_5_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_5_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_5_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_5_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.7, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_7_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_7_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_7_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_7_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.9, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_9_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_9_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_9_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph7_9_5.txt", row.names=FALSE, col.names=FALSE, sep=",")


cors = matrix(0.9, k, k)
for (x in 1: k) {
  cors[x, x] = 1
}

means = matrix(0.1, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_1_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_1_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_1_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_1_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.3, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_3_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_3_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_3_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_3_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.5, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_5_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_5_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_5_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_5_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.7, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_7_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_7_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_7_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_7_5.txt", row.names=FALSE, col.names=FALSE, sep=",")

means = matrix(0.9, 1, k)
cp = bincorr2commonprob(means, cors)
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_9_2.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_9_3.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_9_4.txt", row.names=FALSE, col.names=FALSE, sep=",")
samples = rmvbin(n, commonprob=cp)
write.table(samples, file="graph9_9_5.txt", row.names=FALSE, col.names=FALSE, sep=",")
